export const Seo = () => {
  return (
    <>
      <title>Maildroppa</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="lang" content="en" />
      <meta name="application-name" content="Maildroppa" />
      <meta itemProp="name" content="Maildroppa" />
      <meta name="description" content="Generated by create next app" />
      <meta
        name="keywords"
        content="maildroppa, maildrop, maildrop.sa, maildrop.sa, maildrop.sa"
      />
      <meta name="robots" content="index, follow" />
      <meta name="googlebot" content="index, follow" />
      <meta name="bingbot" content="index, follow" />
      <meta
        name="msapplication-starturl"
        content={"https://maildroppa.vercel.app"}
      />
      <link
        rel="icon"
        href="https://tailwindui.com/img/logos/workflow-mark-indigo-500.svg"
      />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link
        rel="apple-touch-icon"
        href="https://tailwindui.com/img/logos/workflow-mark-indigo-500.svg"
      />
    </>
  );
};
